name = "pin"
compatibility_date = "2024-05-17"
main = "src/index.ts"

[assets]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "pin"
database_id = "5f0cd562-b00b-4716-9844-ab0fa3e943a8"
